//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medical_encyclopedia_DB62.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disease
    {
        public int Id { get; set; }
        public string Disease_name { get; set; }
        public Nullable<int> Disease_category { get; set; }
        public string Disease_symptoms { get; set; }
    
        public virtual Disease Disease1 { get; set; }
        public virtual Disease Disease2 { get; set; }
    }
}
